services:
  - type: web
    name: dopi-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: PI_API_KEY
        sync: false
      - key: PLATFORM_API_URL
        value: https://api.minepi.com
      - key: MONGODB_DATABASE_NAME
        sync: false
      - key: MONGODB_USERNAME
        sync: false
      - key: MONGODB_PASSWORD
        sync: false
      - key: MONGO_HOST
        sync: false
      - key: FRONTEND_URL
        sync: false

  - type: static
    name: dopi-frontend
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars: []
